// Auto generated by @meng-xi/vite-plugin autoImport
// @ts-nocheck
export {}

declare global {
  // from 'vue'
  const ref: typeof import('vue')['ref']
  const reactive: typeof import('vue')['reactive']
  const computed: typeof import('vue')['computed']
  const watch: typeof import('vue')['watch']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']

}