export { JS_KEYWORDS, stripCommentsAndStrings } from './common/code/index.mjs';
export { calculateGzipSize } from './common/compress/index.mjs';
export { runWithConcurrency } from './common/concurrency/index.mjs';
export { parseEnvContent } from './common/env/index.mjs';
export { DateFormatOptions, calcRatio, formatDate, formatFileSize, getDateFormatParams, parsePluginTemplate, parseTemplate, parseTemplateWithDelimiter } from './common/format/index.mjs';
export { CopyOptions, CopyResult, ScanDirectoryOptions, ScannedFile, checkSourceExists, copySourceToTarget, deleteFiles, resolveReportPath, scanAndMapFiles, scanDirectory, shouldUpdateFileContent, writeFileContent, writeFileSyncSafely, writeJsonReport } from './common/fs/index.mjs';
export { generateRandomHash } from './common/hash/index.mjs';
export { SanitizeRuleOptions, escapeHtmlAttr, injectBeforeTag, injectHeadAndBody, sanitizeContent } from './common/html/index.mjs';
export { deepMerge } from './common/object/index.mjs';
export { isExtensionIncluded, isPathExcluded, isPreCompressed, normalizePath } from './common/path/index.mjs';
export { makeCallback } from './common/script/index.mjs';
export { escapeRegex, stripJsonComments, toCamelCase, toPascalCase } from './common/string/index.mjs';
export { ANSI, ANSI_REGEX, stripAnsi } from './common/ui/index.mjs';
export { V as Validator } from './shared/vite-plugin.DRRlWY8P.mjs';
export { validateCallbackFields, validateGlobalName, validateNoScriptInTemplate } from './common/validation/index.mjs';
export { BasePlugin, BasePluginOptions, OptionsNormalizer, PluginFactory, PluginWithInstance, createPluginFactory } from './factory/index.mjs';
export { Logger } from './logger/index.mjs';
export { BuildPhase, BuildProgressOptions, ProgressFormat, ProgressTheme, buildProgress } from './plugins/analyze/buildProgress/index.mjs';
export { BundleAnalysisResult, BundleAnalyzerOptions, BundleOutputFormat, ChunkStats, ComparisonDiff, FileTypeDistribution, ModuleStats, SizeWarning, bundleAnalyzer } from './plugins/analyze/bundleAnalyzer/index.mjs';
export { CompressAlgorithm, CompressAssetsOptions, CompressStats, CompressSummary, compressAssets } from './plugins/compress/compressAssets/index.mjs';
export { ConvertMapping, FormatQualityOptions, ImageFormat, ImageOptimizeStats, ImageOptimizeSummary, ImageOptimizerOptions, SvgoOptions, SvgoPlugin, imageOptimizer } from './plugins/compress/imageOptimizer/index.mjs';
export { AssetGroup, AssetManifestOptions, AssetManifestResult, AssetMap, CustomFormatter, ManifestOutputFormat, WebpackEntryAsset, WebpackManifestOutput, assetManifest } from './plugins/copy/assetManifest/index.mjs';
export { CopyFileOptions, copyFile } from './plugins/copy/copyFile/index.mjs';
export { AutoImportOptions, ImportMapping, ResolvedImport, ScannedModule, TransformResult, autoImport } from './plugins/generate/autoImport/index.mjs';
export { GenerateRouterOptions, NameStrategy, OutputFormat, RouteConfig, RouteMeta, UniAppPageConfig, UniAppPagesJson, UniAppTabBarConfig, generateRouter } from './plugins/generate/generateRouter/index.mjs';
export { GenerateVersionOptions, OutputType, VersionFormat, VersionInfo, generateVersion } from './plugins/generate/generateVersion/index.mjs';
export { EnvFailAction, EnvGuardOptions, EnvGuardResult, RuntimeGuardMode, envGuard } from './plugins/guard/envGuard/index.mjs';
export { FaviconManagerOptions, Icon, IconOptions, faviconManager } from './plugins/inject/faviconManager/index.mjs';
export { HtmlInjectOptions, InjectRule, InjectionLogEntry, htmlInject } from './plugins/inject/htmlInject/index.mjs';
export { AutoBindMode, AutoHideOn, DebounceHide, DelayShow, LoadingCallbacks, LoadingManager, LoadingManagerOptions, LoadingPosition, LoadingStyle, MinDisplayTime, RequestFilter, SpinnerType, TransitionConfig, loadingManager } from './plugins/inject/loadingManager/index.mjs';
export { PromptStyle, VersionSource, VersionUpdateCheckerOptions, versionUpdateChecker } from './plugins/inject/versionUpdateChecker/index.mjs';
export { DelayConfig, ProxyLogEntry, ProxyLogLevel, ProxyManagerOptions, ProxyRule, ResolvedProxyRule, proxyManager } from './plugins/proxy/proxyManager/index.mjs';
export { C as ConditionType, D as DualInjectResult, H as HtmlInjectResult, I as InjectCondition, a as InjectPosition, S as SecurityConfig, b as SelectorMatch } from './shared/vite-plugin.BI9taN75.mjs';
export { L as LoggerOptions, P as PluginLogger } from './shared/vite-plugin.BmNqGOzh.mjs';
import 'vite';
import 'node:http';
