import fs from 'node:fs'
import path from 'node:path'
import type { ResolvedImport } from '../types'

/**
 * 生成 TypeScript 类型声明文件内容
 *
 * @param imports 解析后的 {@link ResolvedImport} 导入映射列表
 * @returns `.d.ts` 文件内容字符串
 *
 * @description 为自动导入的标识符生成全局类型声明，
 * 使 TypeScript 能够识别这些全局可用的标识符，
 * 避免 "Cannot find name" 错误。
 *
 * **生成格式：**
 * ```typescript
 * // Auto generated by @meng-xi/vite-plugin autoImport
 * // @ts-nocheck
 * export {}
 *
 * declare global {
 *   // from 'vue'
 *   const ref: typeof import('vue')['ref']
 *   const reactive: typeof import('vue')['reactive']
 *
 *   // from 'react'
 *   const React: typeof import('react')['default']
 * }
 * }
 * ```
 *
 * **声明规则：**
 * - 命名导出声明为 `const name: typeof import('module')['name']`
 * - 默认导出声明为 `const name: typeof import('module')['default']`
 * - 按模块分组，每组添加注释标明来源模块
 *
 * @example
 * ```typescript
 * generateDtsContent([
 *   { module: 'vue', name: 'ref', isDefault: false },
 *   { module: 'react', name: 'React', isDefault: true }
 * ])
 * ```
 */
export function generateDtsContent(imports: ResolvedImport[]): string {
	const lines: string[] = []

	lines.push('// Auto generated by @meng-xi/vite-plugin autoImport')
	lines.push('// @ts-nocheck')
	lines.push('export {}')
	lines.push('')

	// 按模块分组
	const moduleMap = new Map<string, ResolvedImport[]>()
	for (const imp of imports) {
		if (!moduleMap.has(imp.module)) {
			moduleMap.set(imp.module, [])
		}
		moduleMap.get(imp.module)!.push(imp)
	}

	lines.push('declare global {')

	for (const [mod, items] of moduleMap) {
		lines.push(`  // from '${mod}'`)

		for (const item of items) {
			if (item.isDefault) {
				// 默认导出：声明为 const 变量，类型为模块的 default 导出
				lines.push(`  const ${item.name}: typeof import('${mod}')['default']`)
			} else {
				// 命名导出：声明为 const 变量，类型为模块的对应命名导出
				lines.push(`  const ${item.name}: typeof import('${mod}')['${item.name}']`)
			}
		}

		lines.push('')
	}

	lines.push('}')

	return lines.join('\n')
}

/**
 * 将类型声明文件写入磁盘
 *
 * @param dtsPath 输出文件的绝对路径
 * @param content 要写入的 `.d.ts` 文件内容
 *
 * @description 将生成的 `.d.ts` 内容写入指定路径。
 * 如果目标目录不存在，会自动递归创建。
 *
 * @throws 当文件写入失败时（如权限不足），抛出 `NodeJS.ErrnoException`
 *
 * @example
 * ```typescript
 * writeDtsFile('/project/src/auto-imports.d.ts', 'declare global { ... }')
 * ```
 */
export function writeDtsFile(dtsPath: string, content: string): void {
	const dir = path.dirname(dtsPath)

	if (!fs.existsSync(dir)) {
		fs.mkdirSync(dir, { recursive: true })
	}

	fs.writeFileSync(dtsPath, content, 'utf-8')
}

/**
 * 检查类型声明文件是否需要更新
 *
 * @param dtsPath 类型声明文件的绝对路径
 * @param newContent 新生成的文件内容
 * @returns 如果需要更新返回 `true`，否则返回 `false`
 *
 * @description 对比现有文件内容与新生成的内容，
 * 仅在内容发生变化时才需要写入，减少不必要的文件 IO 操作。
 * 内部使用 {@link writeFileIfChanged} 的同步版本逻辑。
 *
 * @example
 * ```typescript
 * if (shouldUpdateDts('/project/src/auto-imports.d.ts', newContent)) {
 *   writeDtsFile('/project/src/auto-imports.d.ts', newContent)
 * }
 * ```
 */
export function shouldUpdateDts(dtsPath: string, newContent: string): boolean {
	if (!fs.existsSync(dtsPath)) return true

	try {
		const existing = fs.readFileSync(dtsPath, 'utf-8')
		return existing !== newContent
	} catch {
		return true
	}
}
