import{createPluginFactory as R,BasePlugin as P}from"../../../factory/index.mjs";import{toCamelCase as F,toPascalCase as v,stripJsonComments as O}from"../../../common/string/index.mjs";import{parsePluginTemplate as S}from"../../../common/format/index.mjs";import{writeFileContent as b,shouldUpdateFileContent as B}from"../../../common/fs/index.mjs";import{resolve as m}from"path";import{existsSync as $,promises as y,watch as T}from"fs";import"../../../logger/index.mjs";import"../../../shared/vite-plugin.DcExl6jd.mjs";import"../../../common/object/index.mjs";import"../../../common/concurrency/index.mjs";function k(){return{inString:!1,stringChar:"",depth:0}}function d(t,e,r){const s=k();for(let n=e;n<t.length;n++){const o=t[n];if(s.inString){o===s.stringChar&&t[n-1]!=="\\"&&(s.inString=!1);continue}if(o==="/"&&n+1<t.length&&t[n+1]==="/"){const u=t.indexOf(`
`,n);n=u===-1?t.length-1:u-1;continue}if(o==="/"&&n+1<t.length&&t[n+1]==="*"){const u=t.indexOf("*/",n+2);n=u===-1?t.length-1:u+1;continue}if(o==='"'||o==="'"||o==="`"){s.inString=!0,s.stringChar=o;continue}if(o==="{"||o==="["||o==="("?s.depth++:(o==="}"||o==="]"||o===")")&&s.depth--,r(o,n,s))return n}return t.length}function p(t,e=!0,r=""){if(t===null)return"null";if(t===void 0)return"undefined";if(typeof t=="string")return`'${t.replace(/\\/g,"\\\\").replace(/'/g,"\\'")}'`;if(typeof t=="number"||typeof t=="boolean")return String(t);if(Array.isArray(t))return"["+t.map(s=>p(s,e,r)).join(", ")+"]";if(typeof t=="object"){const s=Object.entries(t);return e?"{ "+s.map(([n,o])=>`${n}: ${p(o,!0,r)}`).join(", ")+" }":`{
${s.map(([n,o])=>`${r}	${n}: ${p(o,!0,r+"	")}`).join(`,
`)}
${r}}`}return String(t)}function J(t){const e=Object.entries(t),r=["{"];for(let s=0;s<e.length;s++){const[n,o]=e[s],u=s<e.length-1?",":"";r.push(`	${n}: ${p(o,!0)}${u}`)}return r.push("}"),r.join(`
`)}function j(t){const e=[];let r=-1;return d(t,0,(s,n,o)=>{s==="{"&&o.depth===1&&(r=n),s==="}"&&o.depth===0&&r>=0&&(e.push(t.substring(r,n+1)),r=-1)}),e}function x(t,e){const r=new RegExp(`\\b${e}\\s*:\\s*`),s=t.match(r);if(!s||s.index===void 0)return null;const n=s.index+s[0].length;let o=n;return d(t,n,(u,i,a)=>{if(a.depth<0||a.depth===0&&u===",")return o=i,!0}),t.substring(n,o)}function h(t,e,r){const s=new RegExp(`(\\b${e}\\s*:\\s*)`),n=t.match(s);if(!n||n.index===void 0){const g=t.lastIndexOf("}"),f=t.substring(0,g),l=f.lastIndexOf(`
`),w=`
${l>=0?f.substring(l+1).match(/^(\s*)/)?.[1]??"	":"	"}${e}: ${r},`;return t.substring(0,g)+w+`
`+t.substring(g)}const o=n.index+n[0].length;let u=o;for(d(t,o,(g,f,l)=>{if(l.depth<0||l.depth===0&&g===",")return u=f,!0});u>o&&/\s/.test(t[u-1]);)u--;const i=t[u],a=i==="}"||i==="]"||i===")",c=r.trim().slice(-1),C=a&&c!=="}"&&c!=="]"&&c!==")"?" ":"";return t.substring(0,n.index)+`${e}: ${r}${C}`+t.substring(u)}function M(t,e){const r=new RegExp(`,?\\s*\\b${e}\\s*:\\s*`),s=t.match(r);if(!s||s.index===void 0)return t;const n=s.index,o=n+s[0].length;let u=o;if(d(t,o,(i,a,c)=>{if(c.depth<0||c.depth===0&&i===",")return u=a,!0}),s[0].startsWith(","))return t.substring(0,n)+t.substring(u);{let i=u;return t[i]===","&&i++,t.substring(0,n)+t.substring(i)}}function W(t,e){const r=[],s=new Set;if(!t.pages?.length)return{routes:r,tabBarPages:s};if(t.tabBar?.list)for(const n of t.tabBar.list)s.add(n.pagePath);for(const n of t.pages)r.push(E(n,"",e,s));if(e.includeSubPackages&&t.subPackages){for(const n of t.subPackages)if(n.pages?.length)for(const o of n.pages)r.push(E(o,n.root,e,s))}return{routes:r,tabBarPages:s}}function E(t,e,r,s){const n=e?`/${e}/${t.path}`:`/${t.path}`,o=t.name||A(n,r),u=N(t,n.replace(/^\//,""),r.metaMapping,s),i={path:n,name:o};return Object.keys(u).length>0&&(i.meta=u),i}function A(t,e){switch(e.nameStrategy){case"path":return t.replace(/\//g,"_").replace(/^_/,"");case"camelCase":return F(t);case"pascalCase":return v(t);case"custom":return e.customNameGenerator(t);default:return F(t)}}function N(t,e,r,s){const n={},o=t.style||{},u=r||{};for(const[i,a]of Object.entries(u))o[i]!==void 0&&(n[a]=o[i]);if(t.meta&&typeof t.meta=="object")for(const[i,a]of Object.entries(t.meta))n[i]=a;return s.has(e)&&(n.isTab=!0),n}function Y(t){return t.split(`
`).map(e=>e.startsWith("	")?e.substring(1):e).join(`
`)}function z(t){const e=new Map,r=D(t);if(!r)return e;const s=j(r);for(const n of s){const o=n.match(/path:\s*['"]([^'"]*)['"]/);o&&e.set(o[1],Y(n.trim()))}return e}function G(t){const e=new Map,r=D(t);if(!r)return e;const s=j(r);for(const n of s){const o=H(n);o.path&&e.set(o.path,o)}return e}function D(t){const e=t.match(/export\s+const\s+routes[^=]*=\s*\[/);if(!e||e.index===void 0)return null;const r=e.index+e[0].length-1;if(r<0)return null;let s=0;for(let n=r;n<t.length;n++){const o=t[n];if(o==="[")s++;else if(o==="]"&&(s--,s===0))return t.substring(r+1,n)}return null}function H(t){const e=t.match(/path:\s*['"]([^'"]*)['"]/),r=t.match(/name:\s*['"]([^'"]*)['"]/),s={path:e?e[1]:""};r&&(s.name=r[1]);const n=x(t,"meta");if(n){const o=V(n.trim());o&&Object.keys(o).length>0&&(s.meta=o)}return s}function V(t){try{const e=t.replace(/(\w+)(?=\s*:)/g,'"$1"').replace(/'([^']*)'/g,'"$1"').replace(/,\s*([\]\}])/g,"$1");return JSON.parse(e)}catch{return null}}function q(t,e){return t.map(r=>{const s=e.get(r.path);if(!s)return r;const n={};return s.meta&&Object.assign(n,s.meta),r.meta&&Object.assign(n,r.meta),{...s,path:r.path,name:r.name,meta:Object.keys(n).length>0?n:void 0}})}const I="1.0.0",_="{name} {date} {version}",U="YYYY-MM-DD HH:mm:ss";function K(t,e,r){const s=Z(e),n=e.outputFormat==="ts"&&e.exportTypes?": RouteConfig[]":"",o=t.map(i=>{const a=r?.get(i.path);return a?tt(a,i):J(i)}).map(i=>i.split(`
`).map(a=>"	"+a).join(`
`)).join(`,
`),u=s?`${s}

`:"";return`${e.headerTemplate?L(e.headerTemplate===!0?_:e.headerTemplate,e.customFields)+`

`:""}${u}/**
 * \u8DEF\u7531\u914D\u7F6E\u5217\u8868
 * @description \u7531 pages.json \u81EA\u52A8\u751F\u6210
 */
export const routes${n} = [
${o}
]

export default routes
`}function L(t,e){return`/**
${X(t,e).map(r=>` * ${r}`).join(`
`)}
 */`}function Q(t){const e=[],r=/\{(name|date(?::[^}]+)?|version|custom:[^}]+)\}/g;let s;for(;(s=r.exec(t))!==null;){const n=s[0],o=s[1];let u;if(o==="name")u="plugin";else if(o==="version")u="version";else if(o==="date"||o.startsWith("date:"))u="date";else if(o.startsWith("custom:"))u=o.substring(7);else continue;e.push({raw:n,tag:u})}return e}function X(t,e){const r=Q(t);if(r.length===0)return t.split(`
`);const s={name:"generate-router",version:I,customFields:e,defaultDateFormat:U};return r.map(n=>{const o=S(n.raw,s);return`@${n.tag} ${o}`})}function Z(t){return!t.exportTypes||t.outputFormat==="js"?"":"import type { RouteConfig } from '@meng-xi/uni-router'"}function tt(t,e){let r=t;return r=h(r,"path",`'${e.path}'`),e.name!==void 0&&(r=h(r,"name",`'${e.name}'`)),e.meta&&Object.keys(e.meta).length>0?r=et(r,e.meta):e.meta&&Object.keys(e.meta).length===0&&(r=M(r,"meta")),r}function et(t,e){const r=x(t,"meta");if(!r)return h(t,"meta",p(e,!0));let s=r.trim();for(const[n,o]of Object.entries(e))s=h(s,n,p(o,!0));return h(t,"meta",s)}function rt(t,e){return typeof e=="string"?"string":typeof e=="boolean"?e?"true":"false":typeof e=="number"?"number":"unknown"}function st(t){const e=Object.entries(t);return e.length===0?"{}":`{ ${e.map(([r,s])=>`${r}: ${rt(r,s)}`).join("; ")} }`}function nt(t,e="@meng-xi/uni-router"){const r=[];r.push(`import '${e}'`),r.push(""),r.push(`declare module '${e}' {`),r.push("  interface RouteNameMap {");for(const s of t){const n=s.name||s.path;s.meta?.title&&r.push(`    /** ${s.meta.title} */`);const o=s.meta?st(s.meta):"{}";r.push(`    ${n}: { path: '${s.path}'; meta: ${o} }`)}return r.push("  }"),r.push("}"),r.join(`
`)}class ot extends P{projectRoot=process.cwd();watcher=null;getPluginName(){return"generate-router"}getDefaultOptions(){return{pagesJsonPath:"src/pages.json",outputPath:"src/router.config.ts",outputFormat:"ts",nameStrategy:"camelCase",includeSubPackages:!0,watch:!0,exportTypes:!0,preserveRouteChanges:!0,metaMapping:{navigationBarTitleText:"title",requireAuth:"requireAuth"},dts:!1,headerTemplate:!1,customFields:{}}}validateOptions(){if(this.validator.field("pagesJsonPath").string().field("outputPath").string().field("outputFormat").enum(["ts","js"]).field("nameStrategy").enum(["path","camelCase","pascalCase","custom"]).validate(),this.options.nameStrategy==="custom"&&!this.options.customNameGenerator)throw new Error("\u5F53 nameStrategy \u4E3A custom \u65F6\uFF0C\u5FC5\u987B\u63D0\u4F9B customNameGenerator")}onConfigResolved(e){super.onConfigResolved(e),this.projectRoot=e.root,this.safeExecute(()=>this.generateRouterConfig(),"\u751F\u6210\u8DEF\u7531\u914D\u7F6E"),e.command==="serve"&&this.startWatching()}destroy(){super.destroy(),this.stopWatching()}async generateRouterConfig(){const e=await this.readPagesJson();if(!e)return;const{routes:r}=W(e,this.options);let s;const n=m(this.projectRoot,this.options.outputPath);if(this.options.preserveRouteChanges&&$(n))try{const u=await y.readFile(n,"utf-8"),i=G(u);if(s=z(u),i.size>0){const a=q(r,i);r.splice(0,r.length,...a),this.logger.info("\u5DF2\u5408\u5E76\u7528\u6237\u5BF9\u8DEF\u7531\u914D\u7F6E\u7684\u4FEE\u6539")}}catch{}const o=K(r,this.options,s);await b(n,o),this.logger.success(`\u8DEF\u7531\u914D\u7F6E\u6587\u4EF6\u5DF2\u751F\u6210: ${n}`),this.logger.info(`\u5171\u751F\u6210 ${r.length} \u6761\u8DEF\u7531\u914D\u7F6E`),await this.generateDtsFile(r)}async readPagesJson(){const e=m(this.projectRoot,this.options.pagesJsonPath);if(!$(e))return this.logger.warn(`pages.json \u6587\u4EF6\u4E0D\u5B58\u5728: ${e}`),null;try{const r=await y.readFile(e,"utf-8");return JSON.parse(O(r))}catch(r){return this.logger.error(`\u89E3\u6790 pages.json \u5931\u8D25: ${r.message}`),null}}async generateDtsFile(e){if(!this.options.dts)return;const r=m(this.projectRoot,typeof this.options.dts=="string"?this.options.dts:"src/router.d.ts"),s=nt(e);B(r,s)&&(await b(r,s),this.logger.success(`\u8DEF\u7531\u7C7B\u578B\u58F0\u660E\u6587\u4EF6\u5DF2\u751F\u6210: ${r}`))}startWatching(){if(!this.options.watch)return;const e=m(this.projectRoot,this.options.pagesJsonPath);$(e)&&(this.watcher=T(e,async r=>{r==="change"&&(this.logger.info("\u68C0\u6D4B\u5230 pages.json \u53D8\u5316\uFF0C\u91CD\u65B0\u751F\u6210\u8DEF\u7531\u914D\u7F6E..."),await this.safeExecute(()=>this.generateRouterConfig(),"\u91CD\u65B0\u751F\u6210\u8DEF\u7531\u914D\u7F6E"))}),this.logger.info(`\u6B63\u5728\u76D1\u542C pages.json \u53D8\u5316: ${e}`))}stopWatching(){this.watcher&&(this.watcher.close(),this.watcher=null)}}const ut=R(ot);export{ut as generateRouter};
