export { AutoImportOptions, BiomelintrcConfig, CacheConfig, DirConfig, DirConfigObject, DirsScanOptions, DtsConfig, DtsConfigObject, EslintrcConfig, ImportInline, ImportMeta, ImportsConfig, InlineImportConfig, PackagePresetOptions, PresetDefinition, Resolver, ScannedModule, TransformResult, VueDirectivesConfig, autoImport } from './autoImport/index.cjs';
export { generateRouter } from './generateRouter/index.cjs';
export { GenerateVersionOptions, OutputType, VersionFormat, VersionInfo, generateVersion } from './generateVersion/index.cjs';
export { generatePages } from './generatePages/index.cjs';
export { GenerateUniOptions, generateUni } from './generateUni/index.cjs';
export { G as GeneratePagesOptions, R as RouteConfigBlock, S as SubPackageConfig, T as TabBarTemplate } from '../../shared/vite-plugin.6nRXIhkp.cjs';
export { G as GenerateRouterOptions, N as NameStrategy, O as OutputFormat, R as RouteConfig, a as RouteMeta } from '../../shared/vite-plugin.BBPyqslH.cjs';
export { U as UniAppPageConfig, a as UniAppPagesJson, b as UniAppTabBarConfig } from '../../shared/vite-plugin.CjZHnjC7.cjs';
import '../../factory/index.cjs';
import 'vite';
import '../../shared/vite-plugin.BmNqGOzh.cjs';
import '../../shared/vite-plugin.DRRlWY8P.cjs';
