export { AutoImportOptions, BiomelintrcConfig, CacheConfig, DirConfig, DirConfigObject, DirsScanOptions, DtsConfig, DtsConfigObject, EslintrcConfig, ImportInline, ImportMeta, ImportsConfig, InlineImportConfig, PackagePresetOptions, PresetDefinition, Resolver, ScannedModule, TransformResult, VueDirectivesConfig, autoImport } from './autoImport/index.mjs';
export { generateRouter } from './generateRouter/index.mjs';
export { GenerateVersionOptions, OutputType, VersionFormat, VersionInfo, generateVersion } from './generateVersion/index.mjs';
export { generatePages } from './generatePages/index.mjs';
export { GenerateUniOptions, generateUni } from './generateUni/index.mjs';
export { G as GeneratePagesOptions, R as RouteConfigBlock, S as SubPackageConfig, T as TabBarTemplate } from '../../shared/vite-plugin.9wMfxHfz.mjs';
export { G as GenerateRouterOptions, N as NameStrategy, O as OutputFormat, R as RouteConfig, a as RouteMeta } from '../../shared/vite-plugin.Dolco-Dj.mjs';
export { U as UniAppPageConfig, a as UniAppPagesJson, b as UniAppTabBarConfig } from '../../shared/vite-plugin.CjZHnjC7.mjs';
import '../../factory/index.mjs';
import 'vite';
import '../../shared/vite-plugin.BmNqGOzh.mjs';
import '../../shared/vite-plugin.DRRlWY8P.mjs';
