import type { ResolvedImport } from '../types'
import { writeFileSyncSafely, shouldUpdateFileContent } from '@/common/fs'

/**
 * JavaScript/TypeScript 保留关键字列表
 *
 * @description 这些关键字不能用作变量标识符，
 * 在生成类型声明时需要跳过，否则会产生语法错误。
 */
const RESERVED_KEYWORDS = new Set([
	'break',
	'case',
	'catch',
	'class',
	'const',
	'continue',
	'debugger',
	'default',
	'delete',
	'do',
	'else',
	'enum',
	'export',
	'extends',
	'false',
	'finally',
	'for',
	'function',
	'if',
	'import',
	'in',
	'instanceof',
	'new',
	'null',
	'return',
	'super',
	'switch',
	'this',
	'throw',
	'true',
	'try',
	'typeof',
	'var',
	'void',
	'while',
	'with',
	'as',
	'implements',
	'interface',
	'let',
	'package',
	'private',
	'protected',
	'public',
	'static',
	'yield',
	'abstract',
	'any',
	'boolean',
	'constructor',
	'declare',
	'get',
	'infer',
	'is',
	'keyof',
	'module',
	'namespace',
	'never',
	'readonly',
	'require',
	'number',
	'object',
	'set',
	'string',
	'symbol',
	'type',
	'undefined',
	'unique',
	'unknown',
	'from',
	'of',
	'async',
	'await',
	'global'
])

/**
 * 生成 TypeScript 类型声明文件内容
 *
 * @param imports 解析后的 {@link ResolvedImport} 导入映射列表
 * @returns `.d.ts` 文件内容字符串
 *
 * @description 为自动导入的标识符生成全局类型声明，
 * 使 TypeScript 能够识别这些全局可用的标识符，
 * 避免 "Cannot find name" 错误。
 *
 * **生成格式：**
 * ```typescript
 * // Auto generated by @meng-xi/vite-plugin autoImport
 * // @ts-nocheck
 * export {}
 *
 * declare global {
 *   // from 'vue'
 *   const ref: typeof import('vue')['ref']
 *   const reactive: typeof import('vue')['reactive']
 *
 *   // from 'react'
 *   const React: typeof import('react')['default']
 * }
 * }
 * ```
 *
 * **声明规则：**
 * - 命名导出声明为 `const name: typeof import('module')['name']`
 * - 默认导出声明为 `const name: typeof import('module')['default']`
 * - 按模块分组，每组添加注释标明来源模块
 *
 * @example
 * ```typescript
 * generateDtsContent([
 *   { module: 'vue', name: 'ref', isDefault: false },
 *   { module: 'react', name: 'React', isDefault: true }
 * ])
 * ```
 */
export function generateDtsContent(imports: ResolvedImport[]): string {
	const lines: string[] = []

	lines.push('// Auto generated by @meng-xi/vite-plugin autoImport')
	lines.push('// @ts-nocheck')
	lines.push('export {}')
	lines.push('')

	// 按模块分组
	const moduleMap = new Map<string, ResolvedImport[]>()
	for (const imp of imports) {
		if (!moduleMap.has(imp.module)) {
			moduleMap.set(imp.module, [])
		}
		moduleMap.get(imp.module)!.push(imp)
	}

	// 去重：同名标识符只保留最后一个模块的声明
	const seenNames = new Set<string>()
	const deduplicatedModuleMap = new Map<string, ResolvedImport[]>()

	// 反向遍历模块，使后配置的模块优先
	const entries = [...moduleMap.entries()].reverse()
	for (const [mod, items] of entries) {
		const dedupedItems: ResolvedImport[] = []
		for (const item of items) {
			if (!seenNames.has(item.name)) {
				seenNames.add(item.name)
				dedupedItems.push(item)
			}
		}
		if (dedupedItems.length > 0) {
			deduplicatedModuleMap.set(mod, dedupedItems)
		}
	}

	lines.push('declare global {')

	// 恢复原始模块顺序输出
	for (const mod of moduleMap.keys()) {
		const dedupedItems = deduplicatedModuleMap.get(mod)
		if (!dedupedItems) continue

		lines.push(`  // from '${mod}'`)

		for (const item of dedupedItems) {
			if (RESERVED_KEYWORDS.has(item.name)) continue
			if (item.isDefault) {
				lines.push(`  const ${item.name}: typeof import('${mod}')['default']`)
			} else {
				lines.push(`  const ${item.name}: typeof import('${mod}')['${item.name}']`)
			}
		}

		lines.push('')
	}

	lines.push('}')

	return lines.join('\n')
}

/**
 * 将类型声明文件写入磁盘
 *
 * @param dtsPath 输出文件的绝对路径
 * @param content 要写入的 `.d.ts` 文件内容
 *
 * @description 将生成的 `.d.ts` 内容写入指定路径。
 * 如果目标目录不存在，会自动递归创建。
 *
 * @throws 当文件写入失败时（如权限不足），抛出 `NodeJS.ErrnoException`
 *
 * @example
 * ```typescript
 * writeDtsFile('/project/src/auto-imports.d.ts', 'declare global { ... }')
 * ```
 */
export function writeDtsFile(dtsPath: string, content: string): void {
	writeFileSyncSafely(dtsPath, content)
}

/**
 * 检查类型声明文件是否需要更新
 *
 * @param dtsPath 类型声明文件的绝对路径
 * @param newContent 新生成的文件内容
 * @returns 如果需要更新返回 `true`，否则返回 `false`
 *
 * @description 对比现有文件内容与新生成的内容，
 * 仅在内容发生变化时才需要写入，减少不必要的文件 IO 操作。
 * 委托给 {@link shouldUpdateFileContent} 实现。
 *
 * @example
 * ```typescript
 * if (shouldUpdateDts('/project/src/auto-imports.d.ts', newContent)) {
 *   writeDtsFile('/project/src/auto-imports.d.ts', newContent)
 * }
 * ```
 */
export function shouldUpdateDts(dtsPath: string, newContent: string): boolean {
	return shouldUpdateFileContent(dtsPath, newContent)
}
