import{createPluginFactory as D,BasePlugin as w}from"../../factory/index.mjs";import{formatDate as m}from"../../common/format/index.mjs";import{writeFileContent as d,shouldUpdateFileContent as E}from"../../common/fs/index.mjs";import{resolve as g}from"path";import{existsSync as f,promises as $,watch as R}from"fs";import"../../logger/index.mjs";import"../../shared/vite-plugin.DcExl6jd.mjs";import"../../common/concurrency/index.mjs";function F(t,r=/[/-]/){return t.replace(/^\/+/,"").split(r).filter(Boolean).map((e,n)=>n===0?e.toLowerCase():e.charAt(0).toUpperCase()+e.slice(1).toLowerCase()).join("")}function P(t,r=/[/-]/){return t.replace(/^\/+/,"").split(r).filter(Boolean).map(e=>e.charAt(0).toUpperCase()+e.slice(1).toLowerCase()).join("")}function O(t){return t.replace(/\/\/.*$/gm,"").replace(/\/\*[\s\S]*?\*\//g,"")}function v(){return{inString:!1,stringChar:"",depth:0}}function h(t,r,e){const n=v();for(let s=r;s<t.length;s++){const o=t[s];if(n.inString){o===n.stringChar&&t[s-1]!=="\\"&&(n.inString=!1);continue}if(o==="/"&&s+1<t.length&&t[s+1]==="/"){const a=t.indexOf(`
`,s);s=a===-1?t.length-1:a-1;continue}if(o==="/"&&s+1<t.length&&t[s+1]==="*"){const a=t.indexOf("*/",s+2);s=a===-1?t.length-1:a+1;continue}if(o==='"'||o==="'"||o==="`"){n.inString=!0,n.stringChar=o;continue}if(o==="{"||o==="["||o==="("?n.depth++:(o==="}"||o==="]"||o===")")&&n.depth--,e(o,s,n))return s}return t.length}function p(t,r=!0,e=""){if(t===null)return"null";if(t===void 0)return"undefined";if(typeof t=="string")return`'${t.replace(/\\/g,"\\\\").replace(/'/g,"\\'")}'`;if(typeof t=="number"||typeof t=="boolean")return String(t);if(Array.isArray(t))return"["+t.map(n=>p(n,r,e)).join(", ")+"]";if(typeof t=="object"){const n=Object.entries(t);return r?"{ "+n.map(([s,o])=>`${s}: ${p(o,!0,e)}`).join(", ")+" }":`{
${n.map(([s,o])=>`${e}	${s}: ${p(o,!0,e+"	")}`).join(`,
`)}
${e}}`}return String(t)}function B(t){const r=Object.entries(t),e=["{"];for(let n=0;n<r.length;n++){const[s,o]=r[n],a=n<r.length-1?",":"";e.push(`	${s}: ${p(o,!0)}${a}`)}return e.push("}"),e.join(`
`)}function b(t){const r=[];let e=-1;return h(t,0,(n,s,o)=>{n==="{"&&o.depth===1&&(e=s),n==="}"&&o.depth===0&&e>=0&&(r.push(t.substring(e,s+1)),e=-1)}),r}function j(t,r){const e=new RegExp(`\\b${r}\\s*:\\s*`),n=t.match(e);if(!n||n.index===void 0)return null;const s=n.index+n[0].length;let o=s;return h(t,s,(a,u,i)=>{if(i.depth<0||i.depth===0&&a===",")return o=u,!0}),t.substring(s,o)}function l(t,r,e){const n=new RegExp(`(\\b${r}\\s*:\\s*)`),s=t.match(n);if(!s||s.index===void 0){const u=t.lastIndexOf("}"),i=t.substring(0,u),c=i.lastIndexOf(`
`),C=`
${c>=0?i.substring(c+1).match(/^(\s*)/)?.[1]??"	":"	"}${r}: ${e},`;return t.substring(0,u)+C+`
`+t.substring(u)}const o=s.index+s[0].length;let a=o;return h(t,o,(u,i,c)=>{if(c.depth<0||c.depth===0&&u===",")return a=i,!0}),t.substring(0,s.index)+`${r}: ${e}`+t.substring(a)}function S(t,r){const e=new RegExp(`,?\\s*\\b${r}\\s*:\\s*`),n=t.match(e);if(!n||n.index===void 0)return t;const s=n.index,o=s+n[0].length;let a=o;if(h(t,o,(u,i,c)=>{if(c.depth<0||c.depth===0&&u===",")return a=i,!0}),n[0].startsWith(","))return t.substring(0,s)+t.substring(a);{let u=a;return t[u]===","&&u++,t.substring(0,s)+t.substring(u)}}function k(t,r){const e=[],n=new Set;if(!t.pages?.length)return{routes:e,tabBarPages:n};if(t.tabBar?.list)for(const s of t.tabBar.list)n.add(s.pagePath);for(const s of t.pages)e.push(y(s,"",r,n));if(r.includeSubPackages&&t.subPackages){for(const s of t.subPackages)if(s.pages?.length)for(const o of s.pages)e.push(y(o,s.root,r,n))}return{routes:e,tabBarPages:n}}function y(t,r,e,n){const s=r?`/${r}/${t.path}`:`/${t.path}`,o=t.name||J(s,e),a=T(t,s.replace(/^\//,""),e.metaMapping,n),u={path:s,name:o};return Object.keys(a).length>0&&(u.meta=a),u}function J(t,r){switch(r.nameStrategy){case"path":return t.replace(/\//g,"_").replace(/^_/,"");case"camelCase":return F(t);case"pascalCase":return P(t);case"custom":return r.customNameGenerator(t);default:return F(t)}}function T(t,r,e,n){const s={},o=t.style||{},a=e||{};for(const[u,i]of Object.entries(a))o[u]!==void 0&&(s[i]=o[u]);if(t.meta&&typeof t.meta=="object")for(const[u,i]of Object.entries(t.meta))s[u]=i;return n.has(r)&&(s.isTab=!0),s}function A(t){const r=new Map,e=x(t);if(!e)return r;const n=b(e);for(const s of n){const o=s.match(/path:\s*['"]([^'"]*)['"]/);o&&r.set(o[1],s.trim())}return r}function M(t){const r=new Map,e=x(t);if(!e)return r;const n=b(e);for(const s of n){const o=N(s);o.path&&r.set(o.path,o)}return r}function x(t){const r=t.match(/export\s+const\s+routes[^=]*=\s*\[/);if(!r||r.index===void 0)return null;const e=r.index+r[0].length-1;if(e<0)return null;let n=0;for(let s=e;s<t.length;s++){const o=t[s];if(o==="[")n++;else if(o==="]"&&(n--,n===0))return t.substring(e,s+1)}return null}function N(t){const r=t.match(/path:\s*['"]([^'"]*)['"]/),e=t.match(/name:\s*['"]([^'"]*)['"]/),n={path:r?r[1]:""};e&&(n.name=e[1]);const s=j(t,"meta");if(s){const o=W(s.trim());o&&Object.keys(o).length>0&&(n.meta=o)}return n}function W(t){try{const r=t.replace(/(\w+)(?=\s*:)/g,'"$1"').replace(/'([^']*)'/g,'"$1"').replace(/,\s*([\]\}])/g,"$1");return JSON.parse(r)}catch{return null}}function Y(t,r){return t.map(e=>{const n=r.get(e.path);if(!n)return e;const s={};return n.meta&&Object.assign(s,n.meta),e.meta&&Object.assign(s,e.meta),{...n,path:e.path,name:e.name,meta:Object.keys(s).length>0?s:void 0}})}const z="0.2.5",G="{name} {date} {version}",L="YYYY-MM-DD HH:mm:ss";function U(t,r,e){const n=H(r),s=r.outputFormat==="ts"?": RouteConfig[]":"",o=t.map(u=>{const i=e?.get(u.path);return i?I(i,u):B(u)}).map(u=>u.split(`
`).map(i=>"	"+i).join(`
`)).join(`,
`),a=n?`${n}

`:"";return`${r.headerTemplate?V(r.headerTemplate===!0?G:r.headerTemplate,r.customFields)+`

`:""}${a}/**
 * \u8DEF\u7531\u914D\u7F6E\u5217\u8868
 * @description \u7531 pages.json \u81EA\u52A8\u751F\u6210
 */
export const routes${s} = [
${o}
]

export default routes
`}function V(t,r){return`/**
${q(t,r).split(`
`).map(e=>` * ${e}`).join(`
`)}
 */`}function q(t,r){let e=t;return e=e.replace(/\{date:([^}]+)\}/g,(n,s)=>m(new Date,`{${s}}`)),e=e.replace(/\{date\}/g,m(new Date,`{${L}}`)),e=e.replace(/\{custom:([^}]+)\}/g,(n,s)=>r?.[s]??`{custom:${s}}`),e=e.replace(/\{name\}/g,"generate-router"),e=e.replace(/\{version\}/g,z),e}function H(t){return!t.exportTypes||t.outputFormat==="js"?"":"import type { RouteConfig } from '@meng-xi/uni-router'"}function I(t,r){let e=t;return e=l(e,"path",`'${r.path}'`),r.name!==void 0&&(e=l(e,"name",`'${r.name}'`)),r.meta&&Object.keys(r.meta).length>0?e=_(e,r.meta):r.meta&&Object.keys(r.meta).length===0&&(e=S(e,"meta")),e}function _(t,r){const e=j(t,"meta");if(!e)return l(t,"meta",p(r,!0));let n=e.trim();for(const[s,o]of Object.entries(r))n=l(n,s,p(o,!0));return l(t,"meta",n)}function K(t,r){return typeof r=="string"?"string":typeof r=="boolean"?r?"true":"false":typeof r=="number"?"number":"unknown"}function Q(t){const r=Object.entries(t);return r.length===0?"{}":`{ ${r.map(([e,n])=>`${e}: ${K(e,n)}`).join("; ")} }`}function X(t,r="@meng-xi/uni-router"){const e=[];e.push(`import '${r}'`),e.push(""),e.push(`declare module '${r}' {`),e.push("  interface RouteNameMap {");for(const n of t){const s=n.name||n.path;n.meta?.title&&e.push(`    /** ${n.meta.title} */`);const o=n.meta?Q(n.meta):"{}";e.push(`    ${s}: { path: '${n.path}'; meta: ${o} }`)}return e.push("  }"),e.push("}"),e.join(`
`)}class Z extends w{projectRoot=process.cwd();watcher=null;getPluginName(){return"generate-router"}getDefaultOptions(){return{pagesJsonPath:"src/pages.json",outputPath:"src/router.config.ts",outputFormat:"ts",nameStrategy:"camelCase",includeSubPackages:!0,watch:!0,exportTypes:!0,preserveRouteChanges:!0,metaMapping:{navigationBarTitleText:"title",requireAuth:"requireAuth"},dts:!1,headerTemplate:!1,customFields:{}}}validateOptions(){if(this.validator.field("pagesJsonPath").string().field("outputPath").string().field("outputFormat").enum(["ts","js"]).field("nameStrategy").enum(["path","camelCase","pascalCase","custom"]).validate(),this.options.nameStrategy==="custom"&&!this.options.customNameGenerator)throw new Error("\u5F53 nameStrategy \u4E3A custom \u65F6\uFF0C\u5FC5\u987B\u63D0\u4F9B customNameGenerator")}onConfigResolved(r){super.onConfigResolved(r),this.projectRoot=r.root,this.safeExecute(()=>this.generateRouterConfig(),"\u751F\u6210\u8DEF\u7531\u914D\u7F6E"),r.command==="serve"&&this.startWatching()}destroy(){super.destroy(),this.stopWatching()}async generateRouterConfig(){const r=await this.readPagesJson();if(!r)return;const{routes:e}=k(r,this.options);let n;const s=g(this.projectRoot,this.options.outputPath);if(this.options.preserveRouteChanges&&f(s))try{const a=await $.readFile(s,"utf-8"),u=M(a);if(n=A(a),u.size>0){const i=Y(e,u);e.splice(0,e.length,...i),this.logger.info("\u5DF2\u5408\u5E76\u7528\u6237\u5BF9\u8DEF\u7531\u914D\u7F6E\u7684\u4FEE\u6539")}}catch{}const o=U(e,this.options,n);await d(s,o),this.logger.success(`\u8DEF\u7531\u914D\u7F6E\u6587\u4EF6\u5DF2\u751F\u6210: ${s}`),this.logger.info(`\u5171\u751F\u6210 ${e.length} \u6761\u8DEF\u7531\u914D\u7F6E`),await this.generateDtsFile(e)}async readPagesJson(){const r=g(this.projectRoot,this.options.pagesJsonPath);if(!f(r))return this.logger.warn(`pages.json \u6587\u4EF6\u4E0D\u5B58\u5728: ${r}`),null;try{const e=await $.readFile(r,"utf-8");return JSON.parse(O(e))}catch(e){return this.logger.error(`\u89E3\u6790 pages.json \u5931\u8D25: ${e.message}`),null}}async generateDtsFile(r){if(!this.options.dts)return;const e=g(this.projectRoot,typeof this.options.dts=="string"?this.options.dts:"src/router.d.ts"),n=X(r);E(e,n)&&(await d(e,n),this.logger.success(`\u8DEF\u7531\u7C7B\u578B\u58F0\u660E\u6587\u4EF6\u5DF2\u751F\u6210: ${e}`))}startWatching(){if(!this.options.watch)return;const r=g(this.projectRoot,this.options.pagesJsonPath);f(r)&&(this.watcher=R(r,async e=>{e==="change"&&(this.logger.info("\u68C0\u6D4B\u5230 pages.json \u53D8\u5316\uFF0C\u91CD\u65B0\u751F\u6210\u8DEF\u7531\u914D\u7F6E..."),await this.safeExecute(()=>this.generateRouterConfig(),"\u91CD\u65B0\u751F\u6210\u8DEF\u7531\u914D\u7F6E"))}),this.logger.info(`\u6B63\u5728\u76D1\u542C pages.json \u53D8\u5316: ${r}`))}stopWatching(){this.watcher&&(this.watcher.close(),this.watcher=null)}}const tt=D(Z);export{tt as generateRouter};
