export { BuildPhase, BuildProgressOptions, ProgressFormat, ProgressTheme, buildProgress } from './analyze/buildProgress/index.mjs';
export { BundleAnalysisResult, BundleAnalyzerOptions, BundleOutputFormat, ChunkStats, ComparisonDiff, FileTypeDistribution, ModuleStats, SizeWarning, bundleAnalyzer } from './analyze/bundleAnalyzer/index.mjs';
export { CompressAlgorithm, CompressAssetsOptions, CompressStats, CompressSummary, compressAssets } from './compress/compressAssets/index.mjs';
export { ConvertMapping, FormatQualityOptions, ImageFormat, ImageOptimizeStats, ImageOptimizeSummary, ImageOptimizerOptions, SvgoOptions, SvgoPlugin, imageOptimizer } from './compress/imageOptimizer/index.mjs';
export { AssetGroup, AssetManifestOptions, AssetManifestResult, AssetMap, CustomFormatter, ManifestOutputFormat, WebpackEntryAsset, WebpackManifestOutput, assetManifest } from './copy/assetManifest/index.mjs';
export { CopyFileOptions, copyFile } from './copy/copyFile/index.mjs';
export { AutoImportOptions, ImportMapping, ResolvedImport, ScannedModule, TransformResult, autoImport } from './generate/autoImport/index.mjs';
export { GenerateRouterOptions, NameStrategy, OutputFormat, RouteConfig, RouteMeta, UniAppPageConfig, UniAppPagesJson, UniAppTabBarConfig, generateRouter } from './generate/generateRouter/index.mjs';
export { GenerateVersionOptions, OutputType, VersionFormat, VersionInfo, generateVersion } from './generate/generateVersion/index.mjs';
export { EnvFailAction, EnvGuardOptions, EnvGuardResult, RuntimeGuardMode, envGuard } from './guard/envGuard/index.mjs';
export { FaviconManagerOptions, Icon, IconOptions, faviconManager } from './inject/faviconManager/index.mjs';
export { HtmlInjectOptions, InjectRule, InjectionLogEntry, htmlInject } from './inject/htmlInject/index.mjs';
export { AutoBindMode, AutoHideOn, DebounceHide, DelayShow, LoadingCallbacks, LoadingManager, LoadingManagerOptions, LoadingPosition, LoadingStyle, MinDisplayTime, RequestFilter, SpinnerType, TransitionConfig, loadingManager } from './inject/loadingManager/index.mjs';
export { PromptStyle, VersionSource, VersionUpdateCheckerOptions, versionUpdateChecker } from './inject/versionUpdateChecker/index.mjs';
export { DelayConfig, ProxyLogEntry, ProxyLogLevel, ProxyManagerOptions, ProxyRule, ResolvedProxyRule, proxyManager } from './proxy/proxyManager/index.mjs';
import '../factory/index.mjs';
import 'vite';
import '../shared/vite-plugin.BmNqGOzh.mjs';
import '../shared/vite-plugin.DRRlWY8P.mjs';
import '../shared/vite-plugin.BI9taN75.mjs';
import 'node:http';
