import type { ImportInline } from '../types'
import { writeFileSyncSafely, shouldUpdateFileContent } from '@/common/fs'
import fs from 'node:fs'

/** JavaScript/TypeScript 保留关键字列表 */
const RESERVED_KEYWORDS = new Set([
	'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default',
	'delete', 'do', 'else', 'enum', 'export', 'extends', 'false', 'finally', 'for',
	'function', 'if', 'import', 'in', 'instanceof', 'new', 'null', 'return', 'super',
	'switch', 'this', 'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with',
	'as', 'implements', 'interface', 'let', 'package', 'private', 'protected', 'public',
	'static', 'yield', 'abstract', 'any', 'boolean', 'constructor', 'declare', 'get',
	'infer', 'is', 'keyof', 'module', 'namespace', 'never', 'readonly', 'require',
	'number', 'object', 'set', 'string', 'symbol', 'type', 'undefined', 'unique',
	'unknown', 'from', 'of', 'async', 'await', 'global',
])

/**
 * 生成 TypeScript 类型声明文件内容（增强版）
 *
 * @param imports ImportInline 列表
 * @param options DTS 生成选项
 * @returns .d.ts 文件内容
 *
 * @description 增强版：
 * - 支持 append/overwrite 模式
 * - 支持 ignoreDts 过滤
 * - 支持类型导入声明
 * - 按模块分组，同名标识符去重
 */
export function generateDtsContent(
	imports: ImportInline[],
	options?: {
		mode?: 'append' | 'overwrite'
		ignoreDts?: Array<string | RegExp>
		preserveExts?: boolean
	}
): string {
	const ignoreDts = options?.ignoreDts ?? []

	// 过滤需要忽略的标识符
	const filteredImports = imports.filter(imp => {
		const name = imp.as || imp.name
		for (const ignore of ignoreDts) {
			if (typeof ignore === 'string' && name === ignore) return false
			if (ignore instanceof RegExp && ignore.test(name)) return false
		}
		return true
	})

	if (filteredImports.length === 0) {
		return ''
	}

	const lines: string[] = []

	lines.push('// Auto generated by @meng-xi/vite-plugin autoImport')
	lines.push('// @ts-nocheck')
	lines.push('export {}')
	lines.push('')

	// 按模块分组
	const moduleMap = new Map<string, ImportInline[]>()
	for (const imp of filteredImports) {
		if (!moduleMap.has(imp.from)) {
			moduleMap.set(imp.from, [])
		}
		moduleMap.get(imp.from)!.push(imp)
	}

	// 去重：同名标识符只保留最后一个模块的声明
	const seenNames = new Set<string>()
	const deduplicatedModuleMap = new Map<string, ImportInline[]>()

	const entries = [...moduleMap.entries()].reverse()
	for (const [mod, items] of entries) {
		const dedupedItems: ImportInline[] = []
		for (const item of items) {
			const name = item.as || item.name
			if (!seenNames.has(name)) {
				seenNames.add(name)
				dedupedItems.push(item)
			}
		}
		if (dedupedItems.length > 0) {
			deduplicatedModuleMap.set(mod, dedupedItems)
		}
	}

	lines.push('declare global {')

	for (const mod of moduleMap.keys()) {
		const dedupedItems = deduplicatedModuleMap.get(mod)
		if (!dedupedItems) continue

		lines.push(`  // from '${mod}'`)

		for (const item of dedupedItems) {
				const name = item.as || item.name
				if (RESERVED_KEYWORDS.has(name)) continue

				if (item.name === '*') {
					// 命名空间导入: const alias: typeof import('mod')
					lines.push(`  const ${name}: typeof import('${mod}')`)
				} else if (item.name === '=') {
					// export assignment 导入: const alias: typeof import('mod')
					lines.push(`  const ${name}: typeof import('${mod}')`)
				} else if (item.isDefault || item.name === 'default') {
					lines.push(`  const ${name}: typeof import('${mod}')['default']`)
				} else {
					lines.push(`  const ${name}: typeof import('${mod}')['${item.name}']`)
				}
			}

		lines.push('')
	}

	lines.push('}')

	return lines.join('\n')
}

/**
 * 将类型声明文件写入磁盘
 *
 * @param dtsPath 输出文件的绝对路径
 * @param content 要写入的 .d.ts 文件内容
 */
export function writeDtsFile(dtsPath: string, content: string): void {
	writeFileSyncSafely(dtsPath, content)
}

/**
 * 检查类型声明文件是否需要更新
 *
 * @param dtsPath 类型声明文件的绝对路径
 * @param newContent 新生成的文件内容
 * @returns 如果需要更新返回 true
 */
export function shouldUpdateDts(dtsPath: string, newContent: string): boolean {
	return shouldUpdateFileContent(dtsPath, newContent)
}

/**
 * 在 append 模式下合并现有 DTS 内容和新生成的内容
 *
 * @param dtsPath DTS 文件路径
 * @param newContent 新生成的 declare global 块内容
 * @returns 合并后的完整文件内容
 *
 * @description append 模式保留文件中 declare global {} 之外的用户自定义内容，
 * 仅替换 declare global 块的内容。
 */
export function mergeDtsContent(dtsPath: string, newContent: string): string {
	if (!fs.existsSync(dtsPath)) {
		return newContent
	}

	try {
		const existingContent = fs.readFileSync(dtsPath, 'utf-8')

		// 提取新的 declare global 块
		const newGlobalMatch = newContent.match(/declare global \{[\s\S]*?\n\}/)
		if (!newGlobalMatch) return newContent

		// 替换现有文件中的 declare global 块
		const existingGlobalMatch = existingContent.match(/declare global \{[\s\S]*?\n\}/)
		if (existingGlobalMatch) {
			return existingContent.replace(
				/declare global \{[\s\S]*?\n\}/,
				newGlobalMatch[0]
			)
		}

		// 现有文件没有 declare global 块，追加
		return existingContent + '\n\n' + newContent
	} catch {
		return newContent
	}
}
